// @ts-ignore
export const ASSETSPATH: string = _ASSETSPATH;

export const THEMES = [
    'AtlanticNight',
    'EvaLight',
    'Nebula',
    'ShadesOfPurple',
    'AtomOneDark',
    'FlatUI',
    'NoctisAzureus',
    'SnazzyLight',
    'AuroraX',
    'Hopscotch',
    'NoctisBordo',
    'SnazzyOperator',
    'HorlaLightTheme',
    'NoctisLux',
    'SublimeMaterialThemeDark',
    'AyuLight',
    'HybridNext',
    'OneDarkPro',
    'SynthWave84',
    'BlulocoLight',
    'KimbieDark',
    'OneMonokai',
    'TokyoNightStorm',
    'CodeSandBox',
    'Lucario',
    'Panda',
    'TomorrowNightBlue',
    'Darktooth',
    'MonokaiDimmed',
    'ReUI',
    'Twilight',
    'MonokaiPro',
    'RemedyDark',
]
